### ISSUE TITLE
FYI: Rust wrapper

### ISSUE THREAD

**Issue by virtualritz** [scrtwpns/mixbox#5]
I made [a Rust wrapper for `pigment-mixing`](https://github.com/virtualritz/pigment-mixing-rs) a while a ago and finally took the time last weekend to write up docs & README and make the repo. public.

It [does not use the `*_u8` functions](https://github.com/virtualritz/pigment-mixing-rs#notes-on-color) because of #1 being unanswered so far.

I can't publish this on [`crates.io`](https://www.crates.io) because there is a 10MB limit on crate size.

Generating the lookup table at runtime would solve this. See also [my comment](https://github.com/scrtwpns/pigment-mixing/issues/3#issuecomment-1024202406) on #3.

**Comment by photon-garden** [comment]
Thank you so much @virtualritz! I was trying to figure out how to play with this code from Rust but have no experience linking with C++ so was running into some problems. Your wrapper made it effortless!

**Comment by virtualritz** [comment]
@photon-garden Feedback welcome (feel free to open issues in the wrapper repo.).

**Comment by scrtwpns** [comment]
Thanks for the heads up!

We were also interested in bringing Mixbox to Rust and decided to make a native Rust implementation for Mixbox 2.0. 

The Rust version of Mixbox is available on [https://crates.io/crates/mixbox](https://crates.io/crates/mixbox)
