### ISSUE TITLE
Publish code to calculate `concs_table`

### ISSUE THREAD

**Issue by virtualritz** [scrtwpns/mixbox#6]
Rationales:

1. The code can probably be parallelized and, if fast enough, would allow creating the table on a client on first run or even on every run.
2. The primaries could be adjusted to use inputs from a space that has a larger gamut than `sRGB`.

**Comment by scrtwpns** [comment]
We managed to reduce the size of the table to less than 200 kB which makes the client-side calculation unnecessary.
